// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsC0SwhIQgiDFHobE4ATTu2RtO14EhaaY',
    appId: '1:800395318825:web:506503da8fcba1841a2e38',
    messagingSenderId: '800395318825',
    projectId: 'sakinah-e45bc',
    authDomain: 'sakinah-e45bc.firebaseapp.com',
    storageBucket: 'sakinah-e45bc.firebasestorage.app',
    measurementId: 'G-F8P7C17T34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSDcInQy0FdnpCHDuctMbetv-WgmDG-Sk',
    appId: '1:800395318825:android:406fec58d6d12d441a2e38',
    messagingSenderId: '800395318825',
    projectId: 'sakinah-e45bc',
    storageBucket: 'sakinah-e45bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHOj4f0_vJLV5E8z3cJC80wiY04xtFXa0',
    appId: '1:800395318825:ios:0ab568052699daf61a2e38',
    messagingSenderId: '800395318825',
    projectId: 'sakinah-e45bc',
    storageBucket: 'sakinah-e45bc.firebasestorage.app',
    androidClientId: '800395318825-4ea2otdtp6llhf6u5cdev9m09it1jjr0.apps.googleusercontent.com',
    iosClientId: '800395318825-cbksigeksnc2g2qimua9m82l0u3b66s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakinah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHOj4f0_vJLV5E8z3cJC80wiY04xtFXa0',
    appId: '1:800395318825:ios:0ab568052699daf61a2e38',
    messagingSenderId: '800395318825',
    projectId: 'sakinah-e45bc',
    storageBucket: 'sakinah-e45bc.firebasestorage.app',
    androidClientId: '800395318825-4ea2otdtp6llhf6u5cdev9m09it1jjr0.apps.googleusercontent.com',
    iosClientId: '800395318825-cbksigeksnc2g2qimua9m82l0u3b66s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakinah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGn-3YseEBh3Uf8YCtq-Nq16iNjpbg4I0',
    appId: '1:800395318825:web:9714f8f72c0ac6aa1a2e38',
    messagingSenderId: '800395318825',
    projectId: 'sakinah-e45bc',
    authDomain: 'sakinah-e45bc.firebaseapp.com',
    storageBucket: 'sakinah-e45bc.firebasestorage.app',
    measurementId: 'G-H9784EL9JX',
  );
}
